### ISSUE TITLE
Roadmap for moving to github.com/aos-dev

### ISSUE THREAD

**Issue by Xuanwo** [aos-dev/go-storage#412]
This project will be moved to organation https://github.com/aos-dev for better maintenance and project layout.

Readmap:

- [x] Move this repo to https://github.com/aos-dev/go-storage
- [x] Change import path and upgrade to v2
- [x] Split all service into separate repos during v2 upgrade
- [x] #363 shoule also be implemented during v2 upgrade
- [x] Update docs
