### ISSUE TITLE
Migrate to go-storage v3.4.2

### ISSUE THREAD

**Issue by Xuanwo** [aos-dev/go-storage#520]
## Workflow

- Create the related issue which titled like `Migrate to go-storage v3.4.2` and update links below.
- Finish the migrations.
- Check the todo to mark as finished.

Take https://github.com/aos-dev/go-service-s3/pull/56 as example.

## Todo List

- [x] https://github.com/aos-dev/go-service-s3
- [x] https://github.com/aos-dev/go-service-gcs
- [x] https://github.com/aos-dev/go-service-cos
- [x] https://github.com/aos-dev/go-service-oss
- [x] https://github.com/aos-dev/go-service-dropbox
- [x] https://github.com/aos-dev/go-service-azblob
- [x] https://github.com/aos-dev/go-service-kodo
- [x] https://github.com/aos-dev/go-service-uss
