### ISSUE TITLE
Implement Multipart Support

### ISSUE THREAD

**Issue by Xuanwo** [aos-dev/go-storage#522]
## Description

Take go-service-s3 implementation as a reference.

Make sure the implementations pass the tests: https://github.com/aos-dev/go-integration-test/pull/12

## Roadmap

- [x] Add multiparter test in [go-integration-tests](https://github.com/aos-dev/go-integration-test)
  - [x] https://github.com/aos-dev/go-integration-test/pull/12
- [x] Implement multiparter for supported services (`?` means we need to check whether this service support multipart or not)
  - [x] azblob (confirmed not support)
  - [x] cos https://github.com/aos-dev/go-service-cos/pull/23
  - [x] dropbox (confirmed not support)
  - [x] fs (confirmed not support)
  - [x] gcs (comfirmed not support)
  - [x] kodo (lack `abortMultipart` and `listParts` interfaces, unsupported now)
  - [x] oss https://github.com/aos-dev/go-service-oss/pull/21
  - [x] qingstor
  - [x] s3 (multipart tests are not passed, should be fixed) https://github.com/aos-dev/go-service-s3/pull/88
  - [x] uss (confirmed not support)

**Comment by Rouzip** [comment]
If you means multipart upload, kodo supports [this](https://developer.qiniu.com/kodo/7458/multipartupload).

**Comment by Xuanwo** [comment]
> If you means multipart upload, kodo supports [this](https://developer.qiniu.com/kodo/7458/multipartupload).

Thanks for the comment, roadmap has been updated.

**Comment by JinnyYi** [comment]
> If you means multipart upload, kodo supports [this](https://developer.qiniu.com/kodo/7458/multipartupload).

Seems there're no `abortMultipartUpload` and `listParts` in Go SDK. Do I miss them or other functions implement them?

**Comment by JinnyYi** [comment]
> > If you means multipart upload, kodo supports [this](https://developer.qiniu.com/kodo/7458/multipartupload).
> 
> Seems there're no `abortMultipartUpload` and `listParts` in Go SDK. Do I miss them or other functions implement them?

![image](https://user-images.githubusercontent.com/82445294/118234442-e8124300-b4c5-11eb-9e49-fedab0735c22.png)

**Comment by Rouzip** [comment]
> > If you means multipart upload, kodo supports [this](https://developer.qiniu.com/kodo/7458/multipartupload).
> 
> Seems there're no `abortMultipartUpload` and `listParts` in Go SDK. Do I miss them or other functions implement them?

Yes, you are right. I have asked the mate who wrote it, he doesn't want to add these two function in GO SDK temporarily, because they are not necessary parts in upload process.

**Comment by Xuanwo** [comment]
> he doesn't want to add these two function in GO SDK temporarily, because they are not necessary parts in upload process.

Well, we don't want the maintainer to add functions **temporarily** either. We expect kodo go SDK can provide those functions officially.

We will deder the multipart support for `kodo` until those features have been released.
