### ISSUE TITLE
Implement SSE support

### ISSUE THREAD

**Issue by Xuanwo** [aos-dev/go-storage#523]
## Description

SSE is Server-Side Encryption, which is used by various applications, we need to support it.

## Notes

- We should calculate the key hash for users which means 
  - we should remove pairs like `sse_customer_key_sha256`.
  - we should calculate the hash while sending the request.

## Roadmap

> If the service does not support this feature, please mark it as done and leave a comment.

- [x] s3 https://github.com/aos-dev/go-service-s3/pull/63 -> part of https://github.com/aos-dev/go-service-s3/issues/51 (Leave this to @JinnyYi )
- [x] qingstor: https://github.com/aos-dev/go-service-qingstor/pull/37 https://github.com/aos-dev/go-service-qingstor/pull/38
- [x] gcs https://github.com/aos-dev/go-service-gcs/pull/19
- [x] oss https://github.com/aos-dev/go-service-oss/pull/14
- [x] cos https://github.com/aos-dev/go-service-cos/pull/17
- [ ] kodo [only support fully managed SSE](https://developer.qiniu.com/kodo/6096/ssencryption), nothing to do
- [ ] uss does not have SSE
- [x] azblob https://github.com/aos-dev/go-service-azblob/pull/13
- [x] add docs https://github.com/aos-dev/site
- [x] add examples https://github.com/aos-dev/go-storage-example
